services:
  - type: web
    name: futbol-bot-uz
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
